In [1]:
print("Hotel Booking Analysis")

Hotel Booking Analysis

In [4]:
import pandas as pd
df = pd.read_csv("hotel_bookings.csv")

In [5]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [9]:
df.shape

(119390, 32)

In [10]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

In [12]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(31994)

Adults + Children + Babies

In [14]:
df['Total_Guests'] = (
    df['adults'] +
    df['children'] +
    df['babies']
)

In [15]:
df[['adults', 'children', 'babies', 'Total_Guests']].head()

   adults  children  babies  Total_Guests
0       2       0.0       0           2.0
1       2       0.0       0           2.0
2       1       0.0       0           1.0
3       1       0.0       0           1.0
4       2       0.0       0           2.0

Weekend Nights + Week Nights

In [16]:
df['Stay_Nights'] = (
    df['stays_in_weekend_nights'] +
    df['stays_in_week_nights']
)

In [17]:
df[
    [
        'stays_in_weekend_nights',
        'stays_in_week_nights',
        'Stay_Nights'
    ]
].head()

   stays_in_weekend_nights  stays_in_week_nights  Stay_Nights
0                        0                     0            0
1                        0                     0            0
2                        0                     1            1
3                        0                     1            1
4                        0                     2            2

is_canceled = 0 → Completed
is_canceled = 1 → Cancelled

In [18]:
df['Booking_Status'] = df['is_canceled'].map({
    0: 'Completed',
    1: 'Cancelled'
})

In [19]:
df[['is_canceled', 'Booking_Status']].head()

   is_canceled Booking_Status
0            0      Completed
1            0      Completed
2            0      Completed
3            0      Completed
4            0      Completed

### BASIC ANALYSIS

In [28]:
#TOTAL BOOKINGS

total_bookings = len(df)

print("Total Bookings:", total_bookings)

Total Bookings: 119390

In [29]:
#CANCELLED BOOKINGS

total_cancelled = (
    df['Booking_Status'] == 'Cancelled'
).sum()

print("Total Cancelled Bookings:", total_cancelled)

Total Cancelled Bookings: 44224

In [30]:
#CANCELLATION RATE

cancellation_rate = (
    total_cancelled / total_bookings
) * 100

print("Cancellation Rate:",
      round(cancellation_rate, 2), "%")

Cancellation Rate: 37.04 %

In [31]:
#AVERAGE DAILY RATE

average_adr = df['adr'].mean()

print("Average ADR:",
      round(average_adr, 2))

Average ADR: 101.83

In [32]:
#AVERAGE STAY DURATION

average_stay = df['Stay_Nights'].mean()

print("Average Stay Duration:",
      round(average_stay, 2),
      "nights")

Average Stay Duration: 3.43 nights

In [33]:
#CITY HOTEL BOOKINGS

city_bookings = (
    df['hotel'] == 'City Hotel'
).sum()

print("City Hotel Bookings:",
      city_bookings)

City Hotel Bookings: 79330

In [34]:
#RESORT HOTEL BOOKINGS

resort_bookings = (
    df['hotel'] == 'Resort Hotel'
).sum()

print("Resort Hotel Bookings:",
      resort_bookings)

Resort Hotel Bookings: 40060

In [35]:
#CREATING A TABLE USING ALL THE ANALYSIS DONE(REFERENCE)

summary = pd.DataFrame({
    'Metric': [
        'Total Bookings',
        'Cancelled Bookings',
        'Cancellation Rate',
        'Average ADR',
        'Average Stay Duration',
        'City Hotel Bookings',
        'Resort Hotel Bookings'
    ],

    'Value': [
        total_bookings,
        total_cancelled,
        round(cancellation_rate, 2),
        round(average_adr, 2),
        round(average_stay, 2),
        city_bookings,
        resort_bookings
    ]
})

summary

                  Metric      Value
0         Total Bookings  119390.00
1     Cancelled Bookings   44224.00
2      Cancellation Rate      37.04
3            Average ADR     101.83
4  Average Stay Duration       3.43
5    City Hotel Bookings   79330.00
6  Resort Hotel Bookings   40060.00

### CLEANED DATA SET

In [37]:
df.to_csv(
    "cleaned_hotel_bookings.csv",
    index=False
)